#!/usr/bin/perl

# Copyright (c) 2021 Spuds <AtomicSpudsGame@gmail.com>
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

use strict;
use warnings;

use Data::Dumper;
use Data::ICal;
use Text::Autoformat;
use Date::Manip::DM6;
use Date::Manip::TZ;
use Date::Manip::Date;
use Getopt::Std;

our $opt_a; # if defined, at output vs ub3r
our $opt_d; # if defined, day of week to match
our $opt_w; # webhook
our $opt_n; # do all but spawn the at jobs

getopts('ad:nw:');

if (!defined($opt_w)) {
	die "Need -w <webhook url>";
	exit(1);
}

my $wh = $opt_w;

my $body = eval { local $/ = undef; <> };
my $calendar = Data::ICal->new(data => $body);

# If parsing failed, try parsing as version 1.0
$calendar = Data::ICal->new(data => $body, vcal10 => 1) unless $calendar;

# If parsing failed, give up :-(
unless ( $calendar ) {
    print "Unable to parse vcalendar: ", $calendar->error_message, "\n";
    print $body;
    exit 1;
}

my @events;

my $vevent = 0;
foreach my $entry ( @{$calendar->{entries}} ) {
    my $properties;

    foreach my $property ( keys %{$entry->properties} ) {
        next unless defined $entry->property($property);
        $properties->{$property} = join(', ', map { $_->decoded_value } @{$entry->property($property)});
        if ( $property eq 'description' ) {
            #$properties->{$property} = eval qq{"$properties->{$property}"};
	    #printf "Description: %s\n", $properties->{$property};

            $properties->{$property} = autoformat $properties->{$property}, {
                all => 1,
                left => 15,
            };
            $properties->{$property} =~ s/^\s*// if defined $properties->{$property};
        } elsif ( $property =~ m{ \A dt (?: start | end ) \z }xms ) {
            if ( $properties->{$property} =~ m{ (\d\d\d\d)(\d\d)(\d\d)T(\d\d)(\d\d)(\d\d) }xms ) {
                $properties->{$property} = "$1-$2-$3 $4:$5:$6";
            }
	}
    }

    my $gtz;

    if ( $entry->ical_entry_type eq 'VEVENT' ) {
    	my $event = { };
	$event->{count} = $vevent++;
	my $prevseen = 0;
        foreach my $key ( qw(summary dtstart dtend) ) {
	    $prevseen = 0;
            next unless defined $properties->{$key};
	    my $info = $properties->{$key};
	    $info =~ s/mailto://gi;
	    $info =~ s/\s*$//;
	    next unless length($info) > 0;
	    $prevseen = 1;
	    my $timeentry = 0;
	    my $k = $key;
	    if ($key eq 'dtstart') {
		$k = "starts";
		$timeentry = 1;
	    } elsif ($key eq 'dtend') {
		$k = "ends";
		$timeentry = 1;
	    }
	    if ($timeentry > 0) {
		my ($loctz,$tz);
		# check if ';TZID=<timezone>' was specified as a parameter
		foreach my $param ( @{$entry->property($key)} ) {
			foreach my $parm (keys %{$param->parameters} ) {
				if ($parm eq "TZID") {
					$tz = ${$param->parameters}{$parm};
				}
			}
		}
		# Default to 'GMT' if not specified anywhere else
		if (!defined($tz)) {
			if (!defined($gtz)) {
				if (!defined($properties->{tzid})) {
					$tz = "GMT";
				} else {
					$tz = $properties->{tzid};
				}
			} else {
				$tz = $gtz;
			}
		}
		my $tzobj = new Date::Manip::TZ;
		$loctz = $tzobj->curr_zone();

		# need Date::Manip::Date back, so had to read Date_ConvTZ() code to do the below:

		my $d = Date::Manip::Date->new();
		my $dmt = $d->tz();
		my $err = $d->parse($info);
		if ($err) {
			printf STDERR "parse of '%s' resulted in error: '%s'\n", $info, $err;
			exit(1);
		}

		my $dval = [ $d->value() ];
		if (! $dval) {
			printf STDERR "value of '%s' resulted in undef\n", $info;
			exit(1);
		}

		my $tmp;
		$tmp = $dmt->zone($tz, $dval);
		if (! $tmp) {
			$tmp = $dmt->zone($tz);
			if (! $tmp) {
				printf STDERR "tz src issue\n";
				exit(1);
			}
		}
		my $from = $tmp;

		$tmp = $dmt->zone($loctz, $dval);
		if (! $tmp) {
			$tmp = $dmt->zone($loctz);
			if (! $tmp) {
				printf STDERR "tz dst issue\n";
				exit(1);
			}
		}
		my $to = $tmp;

		($err, $dval) = $dmt->convert($dval, $from, $to);
		if ($err) {
			printf STDERR "dmt->convert() err = '%s'\n", $err;
			exit(1);
		}
		#printf STDERR "dval is a %s, contents:\n", ref($dval);
		#print STDERR Dumper($dval);
		#print STDERR "\n";
		$d->set('date', $dval);
		#printf STDERR "d is a %s, contents:\n", ref($d);
		#print STDERR Dumper($d);
		#print STDERR "\n";

		$info = $d;

	    }
	    if (defined($info)) {
		#printf STDERR "event->{%s} = { %s }\n", $k, ref($info);
		$event->{$k} = $info;
	    }
        }
	push @events, $event;
    } elsif ( $entry->ical_entry_type eq 'VTIMEZONE') {
	if (defined($properties->{tzid})) {
		$gtz = $properties->{tzid};
	}
    } else {
        print "WARNING: Unknown entry type: ", $entry->ical_entry_type, "\n";
    }
}

my $now = Date::Manip::Date->new();
$now->parse("now");
my $nows = $now->secs_since_1970_GMT();
foreach my $event (sort { $a->{starts}->cmp($b->{starts}) } @events) {
	my $starts = $event->{starts}->secs_since_1970_GMT();

	my ($pdt,$mdt,$cdt,$edt);
	my ($h,$ampm,$dow) = $event->{starts}->printf("%k","%p","%A");
	if (defined($opt_d)) {
		if ($opt_d ne $dow) {
			next;
		}
	}
	$h =~ s/^\s+//;
	$ampm = lc($ampm);
	my $pacific = $h - 2;
	if ($pacific < 12) {
		$pdt = "${pacific}am";
	} else {
		if ($pacific > 12) {
			$pacific = $pacific - 12;
		}
		$pdt = "${pacific}pm";
	}
	my $mountain = $h - 1;
	if ($mountain < 12) {
		$mdt = "${mountain}am";
	} else {
		if ($mountain > 12) {
			$pacific = $pacific - 12;
		}
		$mdt = "${mountain}pm";
	}
	my $central = $h;
	if ($central > 12) {
		$central = $central - 12;
	}
	$cdt = ${central}.$ampm;
	my $eastern = $h + 1;
	if ($eastern > 12) {
		$eastern = $eastern - 12;
	}
	$edt = ${eastern}.$ampm;
	# always afternoon
	my $hour = "$pdt/$mdt/$cdt/$edt PDT/MDT/CDT/EDT";

	foreach my $w ((2880,1440,120,60,45,30,10)) {
		my $m = $w;
		if (!defined($event->{starts})) {
			printf STDERR "Event '%s' starts is undef\n", $event->{summary};
			exit(1);
		}
		my $warns = $starts - $nows;
		$warns -= ($m * 60);
		if (!defined($warns)) {
			print STDERR "warns undef!\n";
			exit(1);
		}
		# adjust for future event if its in thee past
		while ($warns < 0) {
			$warns += 7*24*3600;
		}
		my $timestr = "";
		my $h = 0;
		while ($m >= 60) {
			$h++;
			$m = $m - 60;
		}
		if ($h > 0) {
			$timestr .= "$h hours ";
		}
		if ($m > 0) {
			$timestr .= "$m minutes";
		}
		my $str;
		if (defined($opt_a)) {
			my $atime = $event->{starts}->printf("%Y%m%d%H%M.%S");
			printf STDERR "at -t $atime\n";
			my $cmd = sprintf "dwebhook %s \"TC Reminder: %s\" ".
				"\"%s on %s at %s \@everyone\"",
				$wh, $event->{summary}, $timestr, $dow, $hour;
			printf STDERR "> %s\n", $cmd;
			if (!defined($opt_n)) {
				open(C,"|at -t $atime");
				printf C "%s\n", $cmd;
				close(C);
			}
			
		} else {
			$str = sprintf "hey b remind \@everyone in %d seconds to takeover in %s on %s at %s (%s)\n",
			$warns, $timestr, $dow, $hour, $event->{summary};
			$str =~ s/\s+/ /g;
			print $str."\n";
		}
	}
	my $warns = $starts - $nows;
	while ($warns < 0) {
		$warns += 7*24*3600;
	}
	if (defined($opt_a)) {
		my $atime = $now->printf("%Y%m%d%H%M.%S");
		printf STDERR "at -t $atime\n";
		my $cmd = sprintf "dwebhook %s \"TC Reminder: %s\" ".
			"\"NOW on %s at %s \@everyone\"",
			$wh, $event->{summary}, $dow, $hour;
		printf STDERR "> %s\n", $cmd;
		if (!defined($opt_n)) {
			open(C,"|at -t $atime");
			printf C "%s\n",$cmd;
			close(C);
		}
	} else {
		printf "hey b remind \@everyone in %d seconds to takeover NOW on %s at %s (%s)\n",
			$warns, $dow, $hour, $event->{summary};
	}
}
